新增我的個人頁面
is1ab/is1ab.github.io pull request #63
Opened 2024-09-27 09:03 UTC by WIFI0000

哈囉，我是WIFI，這個是新版的個人頁面，期待可以更新到實驗室的網站上。
辛苦了，感謝審核~

2024-09-27 12:57 UTC, ntut-xuan commented
因為他以為你的 Description 是 `.rst`，reStructuredText 的 h1 是底下加一堆 `-`，像這樣。

```rst
標題
-------------
```

2024-09-27 12:58 UTC, ntut-xuan submitted a review, later dismissed
LGTM.

2024-09-27 12:59 UTC, ntut-xuan requested changes
看起來這個 PR 沒有問題，但請先解決掉 conflict 的問題。

2024-10-05 02:46 UTC, WIFI0000 commented
---------------------
本來還以為要整個檔案整理，因為舊的"MemberRaceExperienceType"和新的"MemberCompetitionExperienceType"不一樣，結果直接在這裡用 resolved conflict 修改好像就可以了..?

2024-10-08 06:09 UTC, ntut-xuan commented
如果解衝突有困難的話，我可以在之後教你，因為衝突可能會在合併分支時發生

2024-10-08 06:10 UTC, merged